apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 1024Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.0.0.98
    path: "/opt/k8s"
  mountOptions:
    - nfsvers=4.2