name: Deploy
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2

    - name: Docker meta
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v1
      with:
        images: accerq/app1
        tag-sha: true

    - name: QEMU
      uses: docker/setup-qemu-action@v1

    - name: Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Bump version and push tag
      id: tagging
      uses: mathieudutour/github-tag-action@v4.5
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64,linux/386
        tags: accerq/app1:${{ steps.tagging.outputs.new_version }}

    - name: teste do run
      run: |
        echo "ALEX CERQUEIRA ${{ steps.tagging.outputs.new_version }}"

    # - name: set deployment
    #   uses: actions-hub/kubectl@master
    #   env:
    #     KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
    #   with:
    #     args: apply -f ./k8s/